redis:
  address: redis:6379
  username: ""
  password: ""
api_key: devkey
api_secret: secret
ws_url: ws://livekit:7880
whip_proxy_enabled: true
development: true

rtc_config:
  use_external_ip: false
  enable_loopback_candidate: false
  node_ip: "127.0.0.1"

logging:
  level: debug
